import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "bn";

interface Translations {
  [key: string]: {
    en: string;
    bn: string;
  };
}

// Comprehensive translation dictionary
export const translations: Translations = {
  // ==================== Settings Page ====================
  "settings": { en: "Settings", bn: "সেটিংস" },
  "settings_desc": { en: "Manage your application preferences and configurations.", bn: "আপনার অ্যাপ্লিকেশন পছন্দ এবং কনফিগারেশন পরিচালনা করুন।" },
  "business_info": { en: "Business Information", bn: "ব্যবসার তথ্য" },
  "business_info_desc": { en: "Update your business details and contact information.", bn: "আপনার ব্যবসার বিবরণ এবং যোগাযোগের তথ্য আপডেট করুন।" },
  "business_name": { en: "Business Name", bn: "ব্যবসার নাম" },
  "phone_number": { en: "Phone Number", bn: "ফোন নম্বর" },
  "address": { en: "Address", bn: "ঠিকানা" },
  "save_changes": { en: "Save Changes", bn: "পরিবর্তন সংরক্ষণ" },
  "notifications": { en: "Notifications", bn: "বিজ্ঞপ্তি" },
  "notifications_desc": { en: "Configure your notification preferences.", bn: "আপনার বিজ্ঞপ্তি পছন্দ কনফিগার করুন।" },
  "low_stock_alerts": { en: "Low Stock Alerts", bn: "কম স্টক সতর্কতা" },
  "low_stock_desc": { en: "Get notified when stock is low", bn: "স্টক কম হলে বিজ্ঞপ্তি পান" },
  "new_order_alerts": { en: "New Order Alerts", bn: "নতুন অর্ডার সতর্কতা" },
  "new_order_desc": { en: "Get notified for new orders", bn: "নতুন অর্ডারের জন্য বিজ্ঞপ্তি পান" },
  "payment_alerts": { en: "Payment Alerts", bn: "পেমেন্ট সতর্কতা" },
  "payment_desc": { en: "Get notified for payments", bn: "পেমেন্টের জন্য বিজ্ঞপ্তি পান" },
  "daily_reports": { en: "Daily Reports", bn: "দৈনিক রিপোর্ট" },
  "daily_reports_desc": { en: "Receive daily summary reports", bn: "দৈনিক সারসংক্ষেপ রিপোর্ট পান" },
  "security": { en: "Security", bn: "নিরাপত্তা" },
  "security_desc": { en: "Manage security settings and access controls.", bn: "নিরাপত্তা সেটিংস এবং অ্যাক্সেস নিয়ন্ত্রণ পরিচালনা করুন।" },
  "change_password": { en: "Change Password", bn: "পাসওয়ার্ড পরিবর্তন" },
  "two_factor": { en: "Two-Factor Authentication", bn: "দ্বি-ফ্যাক্টর প্রমাণীকরণ" },
  "active_sessions": { en: "Active Sessions", bn: "সক্রিয় সেশন" },
  "access_logs": { en: "Access Logs", bn: "অ্যাক্সেস লগ" },
  "appearance": { en: "Appearance", bn: "চেহারা" },
  "appearance_desc": { en: "Customize the look and feel of your dashboard.", bn: "আপনার ড্যাশবোর্ডের চেহারা কাস্টমাইজ করুন।" },
  "dark_mode": { en: "Dark Mode", bn: "ডার্ক মোড" },
  "dark_mode_desc": { en: "Use dark theme", bn: "ডার্ক থিম ব্যবহার করুন" },
  "language": { en: "Language", bn: "ভাষা" },
  "language_desc": { en: "Select your preferred language", bn: "আপনার পছন্দের ভাষা নির্বাচন করুন" },
  "english": { en: "English", bn: "ইংরেজি" },
  "bangla": { en: "বাংলা", bn: "বাংলা" },
  "data_management": { en: "Data Management", bn: "ডেটা ম্যানেজমেন্ট" },
  "data_management_desc": { en: "Manage your data, backups, and exports.", bn: "আপনার ডেটা, ব্যাকআপ এবং এক্সপোর্ট পরিচালনা করুন।" },
  "export_data": { en: "Export Data", bn: "ডেটা এক্সপোর্ট" },
  "backup_database": { en: "Backup Database", bn: "ডেটাবেস ব্যাকআপ" },
  "clear_cache": { en: "Clear Cache", bn: "ক্যাশ মুছুন" },
  "settings_saved": { en: "Settings saved successfully", bn: "সেটিংস সফলভাবে সংরক্ষিত" },
  "cache_cleared": { en: "Cache cleared successfully", bn: "ক্যাশ সফলভাবে মুছে ফেলা হয়েছে" },
  "export_started": { en: "Export started...", bn: "এক্সপোর্ট শুরু হয়েছে..." },
  "backup_created": { en: "Backup created successfully", bn: "ব্যাকআপ সফলভাবে তৈরি হয়েছে" },

  // ==================== Profile Page ====================
  "profile": { en: "Profile", bn: "প্রোফাইল" },
  "profile_desc": { en: "Manage your personal information and account settings.", bn: "আপনার ব্যক্তিগত তথ্য এবং অ্যাকাউন্ট সেটিংস পরিচালনা করুন।" },
  "edit_profile": { en: "Edit Profile", bn: "প্রোফাইল সম্পাদনা" },
  "edit_profile_desc": { en: "Update your personal information.", bn: "আপনার ব্যক্তিগত তথ্য আপডেট করুন।" },
  "full_name": { en: "Full Name", bn: "পূর্ণ নাম" },
  "enter_full_name": { en: "Enter your full name", bn: "আপনার পূর্ণ নাম লিখুন" },
  "enter_phone": { en: "Enter phone number", bn: "ফোন নম্বর লিখুন" },
  "email": { en: "Email", bn: "ইমেইল" },
  "email_readonly": { en: "Email cannot be changed", bn: "ইমেইল পরিবর্তন করা যাবে না" },
  "profile_updated": { en: "Profile updated successfully", bn: "প্রোফাইল সফলভাবে আপডেট হয়েছে" },
  "avatar_updated": { en: "Profile picture updated", bn: "প্রোফাইল ছবি আপডেট হয়েছে" },
  "error_loading_profile": { en: "Error loading profile", bn: "প্রোফাইল লোড করতে সমস্যা" },
  "error_updating_profile": { en: "Error updating profile", bn: "প্রোফাইল আপডেট করতে সমস্যা" },
  "error_uploading_avatar": { en: "Error uploading image", bn: "ছবি আপলোড করতে সমস্যা" },
  "invalid_image": { en: "Please select an image file", bn: "একটি ছবি ফাইল নির্বাচন করুন" },
  "image_too_large": { en: "Image must be less than 2MB", bn: "ছবি ২MB এর কম হতে হবে" },
  "unnamed_user": { en: "Unnamed User", bn: "নামহীন ব্যবহারকারী" },
  "account_info": { en: "Account Information", bn: "অ্যাকাউন্ট তথ্য" },
  "account_info_desc": { en: "Your account details and role.", bn: "আপনার অ্যাকাউন্ট বিবরণ এবং ভূমিকা।" },
  "role": { en: "Role", bn: "ভূমিকা" },
  "no_role": { en: "No role assigned", bn: "কোন ভূমিকা নির্ধারিত নেই" },
  "member_since": { en: "Member Since", bn: "সদস্য হয়েছেন" },
  "unknown": { en: "Unknown", bn: "অজানা" },

  // ==================== Dashboard Navigation ====================
  "dashboard": { en: "Dashboard", bn: "ড্যাশবোর্ড" },
  "overview": { en: "Dashboard", bn: "ড্যাশবোর্ড" },
  "daily_sales": { en: "Daily Sales", bn: "দৈনিক বিক্রয়" },
  "daily_expenses": { en: "Daily Expenses", bn: "দৈনিক খরচ" },
  "analysis": { en: "Analytics", bn: "বিশ্লেষণ" },
  "lpg_stock": { en: "LPG Stock", bn: "এলপিজি স্টক" },
  "stove_stock": { en: "Gas Stove", bn: "গ্যাস চুলা" },
  "regulators": { en: "Regulators", bn: "রেগুলেটর" },
  "product_pricing": { en: "Product Pricing", bn: "পণ্যের মূল্য" },
  "online_delivery": { en: "Online Delivery", bn: "অনলাইন ডেলিভারি" },
  "pos": { en: "Point of Sale", bn: "পয়েন্ট অফ সেল" },
  "customers": { en: "Customers", bn: "গ্রাহক" },
  "staff_salary": { en: "Staff Salary", bn: "কর্মী বেতন" },
  "vehicle_cost": { en: "Vehicle Cost", bn: "গাড়ির খরচ" },
  "community": { en: "LPG Community", bn: "এলপিজি কমিউনিটি" },
  "search": { en: "Search & Reports", bn: "অনুসন্ধান ও রিপোর্ট" },
  "logout": { en: "Sign Out", bn: "সাইন আউট" },
  "exchange": { en: "Exchange", bn: "এক্সচেঞ্জ" },
  "more": { en: "More", bn: "আরও" },
  "all_modules": { en: "All Modules", bn: "সব মডিউল" },
  // ==================== Dashboard Overview ====================
  "welcome_back": { en: "Welcome back!", bn: "স্বাগতম!" },
  "dashboard_subtitle": { en: "Here's what's happening with your LPG business in Bangladesh today.", bn: "আজ আপনার বাংলাদেশে এলপিজি ব্যবসার অবস্থা এখানে দেখুন।" },
  "todays_revenue": { en: "Today's Revenue", bn: "আজকের আয়" },
  "monthly_revenue": { en: "Monthly Revenue", bn: "মাসিক আয়" },
  "active_orders": { en: "Active Orders", bn: "সক্রিয় অর্ডার" },
  "total_customers": { en: "Total Customers", bn: "মোট গ্রাহক" },
  "from_today_sales": { en: "From today's sales", bn: "আজকের বিক্রয় থেকে" },
  "this_month_total": { en: "This month's total", bn: "এই মাসের মোট" },
  "orders_in_progress": { en: "Orders in progress", bn: "চলমান অর্ডার" },
  "registered_customers": { en: "Registered customers", bn: "নিবন্ধিত গ্রাহক" },
  "recent_activities": { en: "Recent Activities", bn: "সাম্প্রতিক কার্যক্রম" },
  "latest_updates": { en: "Latest updates from your LPG operations", bn: "আপনার এলপিজি কার্যক্রমের সর্বশেষ আপডেট" },
  "no_recent_activities": { en: "No recent activities. Start by creating orders or making sales!", bn: "কোন সাম্প্রতিক কার্যক্রম নেই। অর্ডার তৈরি বা বিক্রয় করে শুরু করুন!" },
  "driver_status": { en: "Driver Status", bn: "ড্রাইভারের অবস্থা" },
  "driver_performance": { en: "Real-time driver performance and status", bn: "রিয়েল-টাইম ড্রাইভারের কর্মক্ষমতা এবং অবস্থা" },
  "quick_actions": { en: "Quick Actions", bn: "দ্রুত কার্যক্রম" },
  "access_key_features": { en: "Access key features of your business management.", bn: "আপনার ব্যবসা পরিচালনার মূল বৈশিষ্ট্যগুলি অ্যাক্সেস করুন।" },
  "delivery_completed": { en: "Delivery completed", bn: "ডেলিভারি সম্পন্ন" },
  "new_order_from": { en: "New order from", bn: "নতুন অর্ডার থেকে" },
  "order_delivered_to": { en: "Order delivered to", bn: "অর্ডার ডেলিভার করা হয়েছে" },
  "order_total": { en: "Order total", bn: "অর্ডার মোট" },
  "payment_received": { en: "Payment received", bn: "পেমেন্ট প্রাপ্ত" },
  "low_stock_alert": { en: "Low stock alert", bn: "কম স্টক সতর্কতা" },
  "items_below_minimum": { en: "items below minimum stock", bn: "আইটেম ন্যূনতম স্টকের নিচে" },
  "loading_activities": { en: "Loading activities...", bn: "কার্যক্রম লোড হচ্ছে..." },
  "todays_sales": { en: "Today's Sales", bn: "আজকের বিক্রয়" },
  "deliveries": { en: "Deliveries", bn: "ডেলিভারি" },

  // ==================== POS Module ====================
  "point_of_sale": { en: "Point of Sale", bn: "পয়েন্ট অফ সেল" },
  "quick_sales_billing": { en: "Quick sales and billing system", bn: "দ্রুত বিক্রয় এবং বিলিং সিস্টেম" },
  "lpg_cylinder": { en: "LPG Cylinder", bn: "এলপিজি সিলিন্ডার" },
  "gas_stove": { en: "Gas Stove", bn: "গ্যাস চুলা" },
  "regulator": { en: "Regulator", bn: "রেগুলেটর" },
  "add_lpg_sale": { en: "Add LPG Cylinder Sale", bn: "এলপিজি সিলিন্ডার বিক্রয় যোগ করুন" },
  "cylinder_type": { en: "Cylinder Type", bn: "সিলিন্ডার প্রকার" },
  "refill": { en: "Refill", bn: "রিফিল" },
  "package": { en: "Package", bn: "প্যাকেজ" },
  "sale_type": { en: "Sale Type", bn: "বিক্রয় প্রকার" },
  "retail": { en: "Retail", bn: "খুচরা" },
  "wholesale": { en: "Wholesale", bn: "পাইকারি" },
  "mouth_size": { en: "Mouth Size", bn: "মুখের আকার" },
  "selling_brand": { en: "Selling Brand", bn: "বিক্রয় ব্র্যান্ড" },
  "return_brand": { en: "Return Brand", bn: "ফেরত ব্র্যান্ড" },
  "weight": { en: "Weight", bn: "ওজন" },
  "price": { en: "Price", bn: "মূল্য" },
  "quantity": { en: "Quantity", bn: "পরিমাণ" },
  "add_to_sale": { en: "Add to Sale", bn: "বিক্রয়ে যোগ করুন" },
  "cart": { en: "Cart", bn: "কার্ট" },
  "customer": { en: "Customer", bn: "গ্রাহক" },
  "customer_name": { en: "Customer Name", bn: "গ্রাহকের নাম" },
  "walk_in_customer": { en: "Walk-in Customer", bn: "ওয়াক-ইন গ্রাহক" },
  "select_customer": { en: "Select Customer", bn: "গ্রাহক নির্বাচন করুন" },
  "subtotal": { en: "Subtotal", bn: "সাবটোটাল" },
  "discount": { en: "Discount", bn: "ছাড়" },
  "total": { en: "Total", bn: "মোট" },
  "complete_sale": { en: "Complete Sale", bn: "বিক্রয় সম্পন্ন" },
  "save_as_due": { en: "Save as Due", bn: "বাকি হিসাবে সংরক্ষণ" },
  "sale_completed": { en: "Sale completed!", bn: "বিক্রয় সম্পন্ন!" },
  "saved_as_due": { en: "Saved as due", bn: "বাকি হিসাবে সংরক্ষিত" },
  "no_items_in_sale": { en: "No items in sale", bn: "বিক্রয়ে কোন আইটেম নেই" },
  "receipt": { en: "Receipt", bn: "রসিদ" },
  "print_receipt": { en: "Print Receipt", bn: "রসিদ প্রিন্ট করুন" },
  "invoice": { en: "Invoice", bn: "চালান" },
  "date": { en: "Date", bn: "তারিখ" },
  "item": { en: "Item", bn: "আইটেম" },
  "rate": { en: "Rate", bn: "দর" },
  "paid": { en: "Paid", bn: "পরিশোধিত" },
  "due": { en: "Due", bn: "বাকি" },
  "thank_you": { en: "Thank you for your business!", bn: "আপনার ব্যবসার জন্য ধন্যবাদ!" },

  // ==================== LPG Stock Module ====================
  "lpg_stock_management": { en: "LPG Stock", bn: "এলপিজি স্টক" },
  "manage_cylinder_inventory": { en: "Manage cylinder inventory by brand", bn: "ব্র্যান্ড অনুযায়ী সিলিন্ডার ইনভেন্টরি পরিচালনা করুন" },
  "search_brands": { en: "Search Brands...", bn: "ব্র্যান্ড খুঁজুন..." },
  "new_brand": { en: "New Brand", bn: "নতুন ব্র্যান্ড" },
  "add_new_lpg_brand": { en: "Add New LPG Brand", bn: "নতুন এলপিজি ব্র্যান্ড যোগ করুন" },
  "brand_details": { en: "Enter the brand details and initial cylinder counts.", bn: "ব্র্যান্ড বিবরণ এবং প্রাথমিক সিলিন্ডার সংখ্যা লিখুন।" },
  "brand_name": { en: "Brand Name", bn: "ব্র্যান্ড নাম" },
  "color": { en: "Color", bn: "রঙ" },
  "brand_indicator_color": { en: "Brand indicator color", bn: "ব্র্যান্ড ইন্ডিকেটর রঙ" },
  "package_cylinder": { en: "Package Cylinder", bn: "প্যাকেজ সিলিন্ডার" },
  "refill_cylinder": { en: "Refill Cylinder", bn: "রিফিল সিলিন্ডার" },
  "empty_cylinder": { en: "Empty Cylinder", bn: "খালি সিলিন্ডার" },
  "problem_cylinder": { en: "Problem Cylinder", bn: "সমস্যা সিলিন্ডার" },
  "add_brand": { en: "Add Brand", bn: "ব্র্যান্ড যোগ করুন" },
  "brand_added": { en: "Brand added successfully", bn: "ব্র্যান্ড সফলভাবে যোগ হয়েছে" },
  "brand_removed": { en: "Brand removed", bn: "ব্র্যান্ড সরানো হয়েছে" },
  "package_cylinders": { en: "Package Cylinders", bn: "প্যাকেজ সিলিন্ডার" },
  "refill_cylinders": { en: "Refill Cylinders", bn: "রিফিল সিলিন্ডার" },
  "empty_cylinders": { en: "Empty Cylinders", bn: "খালি সিলিন্ডার" },
  "problem_cylinders": { en: "Problem Cylinders", bn: "সমস্যা সিলিন্ডার" },
  "sl_no": { en: "Sl. NO.", bn: "ক্রম নং" },
  "brand": { en: "Brand", bn: "ব্র্যান্ড" },
  "status": { en: "Status", bn: "অবস্থা" },
  "actions": { en: "Actions", bn: "কার্যক্রম" },
  "in_stock": { en: "In Stock", bn: "স্টকে আছে" },
  "out_of_stock": { en: "Out of Stock", bn: "স্টক নেই" },
  "issues": { en: "Issues", bn: "সমস্যা" },
  "no_brands_found": { en: "No brands found. Add your first LPG brand.", bn: "কোন ব্র্যান্ড পাওয়া যায়নি। আপনার প্রথম এলপিজি ব্র্যান্ড যোগ করুন।" },

  // ==================== Customer Management ====================
  "customer_management": { en: "Customer Management", bn: "গ্রাহক ব্যবস্থাপনা" },
  "manage_due_paid": { en: "Manage due and paid customers", bn: "বাকি এবং পরিশোধিত গ্রাহক পরিচালনা করুন" },
  "due_customers": { en: "Due Customers", bn: "বাকি গ্রাহক" },
  "paid_customers": { en: "Paid Customers", bn: "পরিশোধিত গ্রাহক" },
  "all_customers": { en: "All Customers", bn: "সকল গ্রাহক" },
  "total_due": { en: "Total Due", bn: "মোট বাকি" },
  "cylinders_due": { en: "Cylinders Due", bn: "সিলিন্ডার বাকি" },
  "add_customer": { en: "Add Customer", bn: "গ্রাহক যোগ করুন" },
  "search_customers": { en: "Search customers...", bn: "গ্রাহক খুঁজুন..." },
  "customer_added": { en: "Customer added successfully", bn: "গ্রাহক সফলভাবে যোগ হয়েছে" },
  "customer_updated": { en: "Customer updated successfully", bn: "গ্রাহক সফলভাবে আপডেট হয়েছে" },
  "payment_recorded": { en: "Payment recorded successfully", bn: "পেমেন্ট সফলভাবে রেকর্ড হয়েছে" },
  "settle_account": { en: "Settle Account", bn: "হিসাব নিষ্পত্তি" },
  "payment_history": { en: "Payment History", bn: "পেমেন্ট ইতিহাস" },
  "amount": { en: "Amount", bn: "পরিমাণ" },
  "notes": { en: "Notes", bn: "নোট" },
  "last_order": { en: "Last Order", bn: "শেষ অর্ডার" },

  // ==================== Exchange Module ====================
  "cylinder_exchange": { en: "Cylinder Exchange", bn: "সিলিন্ডার এক্সচেঞ্জ" },
  "exchange_cylinders": { en: "Exchange LPG cylinders with other businesses", bn: "অন্যান্য ব্যবসার সাথে এলপিজি সিলিন্ডার এক্সচেঞ্জ করুন" },
  "from_brand": { en: "From Brand", bn: "থেকে ব্র্যান্ড" },
  "to_brand": { en: "To Brand", bn: "প্রতি ব্র্যান্ড" },
  "from_weight": { en: "From Weight", bn: "থেকে ওজন" },
  "to_weight": { en: "To Weight", bn: "প্রতি ওজন" },
  "exchange_quantity": { en: "Exchange Quantity", bn: "এক্সচেঞ্জ পরিমাণ" },
  "post_exchange": { en: "Post Exchange", bn: "এক্সচেঞ্জ পোস্ট করুন" },
  "exchange_posted": { en: "Exchange offer posted successfully", bn: "এক্সচেঞ্জ অফার সফলভাবে পোস্ট হয়েছে" },
  "pending_exchanges": { en: "Pending Exchanges", bn: "অপেক্ষমাণ এক্সচেঞ্জ" },
  "my_exchanges": { en: "My Exchanges", bn: "আমার এক্সচেঞ্জ" },
  "no_exchanges": { en: "No exchange offers yet", bn: "এখনো কোন এক্সচেঞ্জ অফার নেই" },

  // ==================== Community Module ====================
  "lpg_community": { en: "LPG Community", bn: "এলপিজি কমিউনিটি" },
  "community_desc": { en: "Connect with other LPG businesses in Bangladesh", bn: "বাংলাদেশে অন্যান্য এলপিজি ব্যবসার সাথে সংযুক্ত হোন" },
  "create_post": { en: "Create Post", bn: "পোস্ট তৈরি করুন" },
  "whats_on_your_mind": { en: "What's on your mind?", bn: "আপনার মনে কি আছে?" },
  "post_title": { en: "Post Title", bn: "পোস্ট শিরোনাম" },
  "post_content": { en: "Post Content", bn: "পোস্ট বিষয়বস্তু" },
  "publish": { en: "Publish", bn: "প্রকাশ করুন" },
  "post_created": { en: "Post created successfully", bn: "পোস্ট সফলভাবে তৈরি হয়েছে" },
  "likes": { en: "Likes", bn: "লাইক" },
  "comments": { en: "Comments", bn: "মন্তব্য" },
  "add_comment": { en: "Add a comment...", bn: "একটি মন্তব্য যোগ করুন..." },
  "recent_exchange_offers": { en: "Recent Exchange Offers", bn: "সাম্প্রতিক এক্সচেঞ্জ অফার" },

  // ==================== Staff Salary Module ====================
  "staff_management": { en: "Staff & Salary", bn: "কর্মী এবং বেতন" },
  "manage_staff_salary": { en: "Manage staff information and salary payments", bn: "কর্মী তথ্য এবং বেতন পেমেন্ট পরিচালনা করুন" },
  "add_staff": { en: "Add Staff", bn: "কর্মী যোগ করুন" },
  "staff_name": { en: "Staff Name", bn: "কর্মীর নাম" },
  "staff_role": { en: "Role", bn: "পদ" },
  "monthly_salary": { en: "Monthly Salary", bn: "মাসিক বেতন" },
  "pay_salary": { en: "Pay Salary", bn: "বেতন দিন" },
  "salary_paid": { en: "Salary paid successfully", bn: "বেতন সফলভাবে দেওয়া হয়েছে" },
  "payment_date": { en: "Payment Date", bn: "পেমেন্ট তারিখ" },
  "total_staff": { en: "Total Staff", bn: "মোট কর্মী" },
  "monthly_payroll": { en: "Monthly Payroll", bn: "মাসিক বেতন তালিকা" },

  // ==================== Vehicle Cost Module ====================
  "vehicle_management": { en: "Vehicle Cost", bn: "গাড়ির খরচ" },
  "manage_vehicle_costs": { en: "Manage vehicle expenses and maintenance", bn: "গাড়ির খরচ এবং রক্ষণাবেক্ষণ পরিচালনা করুন" },
  "add_vehicle": { en: "Add Vehicle", bn: "গাড়ি যোগ করুন" },
  "vehicle_name": { en: "Vehicle Name", bn: "গাড়ির নাম" },
  "license_plate": { en: "License Plate", bn: "লাইসেন্স প্লেট" },
  "add_cost": { en: "Add Cost", bn: "খরচ যোগ করুন" },
  "cost_type": { en: "Cost Type", bn: "খরচের ধরণ" },
  "fuel": { en: "Fuel", bn: "জ্বালানি" },
  "maintenance": { en: "Maintenance", bn: "রক্ষণাবেক্ষণ" },
  "repair": { en: "Repair", bn: "মেরামত" },
  "insurance": { en: "Insurance", bn: "বীমা" },
  "other": { en: "Other", bn: "অন্যান্য" },
  "total_vehicles": { en: "Total Vehicles", bn: "মোট গাড়ি" },
  "total_costs": { en: "Total Costs", bn: "মোট খরচ" },

  // ==================== Daily Sales/Expenses ====================
  "daily_sales_report": { en: "Daily Sales Report", bn: "দৈনিক বিক্রয় রিপোর্ট" },
  "track_daily_sales": { en: "Track and manage your daily sales", bn: "আপনার দৈনিক বিক্রয় ট্র্যাক এবং পরিচালনা করুন" },
  "daily_expenses_report": { en: "Daily Expenses Report", bn: "দৈনিক খরচ রিপোর্ট" },
  "track_daily_expenses": { en: "Track and manage your daily expenses", bn: "আপনার দৈনিক খরচ ট্র্যাক এবং পরিচালনা করুন" },
  "add_expense": { en: "Add Expense", bn: "খরচ যোগ করুন" },
  "expense_category": { en: "Category", bn: "বিভাগ" },
  "expense_description": { en: "Description", bn: "বিবরণ" },
  "expense_added": { en: "Expense added successfully", bn: "খরচ সফলভাবে যোগ হয়েছে" },

  // ==================== Stove & Regulator ====================
  "stove_management": { en: "Gas Stove Stock", bn: "গ্যাস চুলা স্টক" },
  "manage_stoves": { en: "Manage gas stove inventory", bn: "গ্যাস চুলা ইনভেন্টরি পরিচালনা করুন" },
  "add_stove": { en: "Add Stove", bn: "চুলা যোগ করুন" },
  "stove_brand": { en: "Brand", bn: "ব্র্যান্ড" },
  "stove_model": { en: "Model", bn: "মডেল" },
  "burners": { en: "Burners", bn: "বার্নার" },
  "stove_price": { en: "Price", bn: "মূল্য" },
  "stove_quantity": { en: "Quantity", bn: "পরিমাণ" },
  "regulator_management": { en: "Regulator Stock", bn: "রেগুলেটর স্টক" },
  "manage_regulators": { en: "Manage regulator inventory", bn: "রেগুলেটর ইনভেন্টরি পরিচালনা করুন" },
  "add_regulator": { en: "Add Regulator", bn: "রেগুলেটর যোগ করুন" },
  "regulator_brand": { en: "Brand", bn: "ব্র্যান্ড" },
  "regulator_type": { en: "Type", bn: "প্রকার" },

  // ==================== Product Pricing ====================
  "product_pricing_management": { en: "Product Pricing", bn: "পণ্যের মূল্য" },
  "manage_product_prices": { en: "Manage product prices and pricing tiers", bn: "পণ্যের মূল্য এবং মূল্য স্তর পরিচালনা করুন" },
  "add_product": { en: "Add Product", bn: "পণ্য যোগ করুন" },
  "product_name": { en: "Product Name", bn: "পণ্যের নাম" },
  "product_type": { en: "Product Type", bn: "পণ্যের ধরণ" },
  "company_price": { en: "Company Price", bn: "কোম্পানি মূল্য" },
  "distributor_price": { en: "Distributor Price", bn: "পরিবেশক মূল্য" },
  "retail_price": { en: "Retail Price", bn: "খুচরা মূল্য" },

  // ==================== Online Delivery ====================
  "online_delivery_management": { en: "Online Delivery", bn: "অনলাইন ডেলিভারি" },
  "manage_online_orders": { en: "Manage online orders and deliveries", bn: "অনলাইন অর্ডার এবং ডেলিভারি পরিচালনা করুন" },
  "new_order": { en: "New Order", bn: "নতুন অর্ডার" },
  "pending_orders": { en: "Pending Orders", bn: "অপেক্ষমাণ অর্ডার" },
  "completed_orders": { en: "Completed Orders", bn: "সম্পন্ন অর্ডার" },
  "delivery_address": { en: "Delivery Address", bn: "ডেলিভারি ঠিকানা" },
  "assign_driver": { en: "Assign Driver", bn: "ড্রাইভার নিয়োগ করুন" },
  "order_status": { en: "Order Status", bn: "অর্ডার অবস্থা" },
  "order_placed": { en: "Order Placed", bn: "অর্ডার দেওয়া হয়েছে" },
  "processing": { en: "Processing", bn: "প্রক্রিয়াধীন" },
  "out_for_delivery": { en: "Out for Delivery", bn: "ডেলিভারির জন্য বের হয়েছে" },
  "delivered": { en: "Delivered", bn: "ডেলিভার হয়েছে" },
  "cancelled": { en: "Cancelled", bn: "বাতিল" },

  // ==================== Analytics ====================
  "analytics_dashboard": { en: "Analytics", bn: "বিশ্লেষণ" },
  "business_insights": { en: "Business insights and performance metrics", bn: "ব্যবসার অন্তর্দৃষ্টি এবং কর্মক্ষমতা মেট্রিক্স" },
  "sales_chart": { en: "Sales Chart", bn: "বিক্রয় চার্ট" },
  "revenue_trend": { en: "Revenue Trend", bn: "আয়ের প্রবণতা" },
  "top_products": { en: "Top Products", bn: "শীর্ষ পণ্য" },
  "customer_growth": { en: "Customer Growth", bn: "গ্রাহক বৃদ্ধি" },
  "this_week": { en: "This Week", bn: "এই সপ্তাহ" },
  "last_week": { en: "Last Week", bn: "গত সপ্তাহ" },
  "this_year": { en: "This Year", bn: "এই বছর" },

  // ==================== Common Actions & Labels ====================
  "welcome": { en: "Welcome", bn: "স্বাগতম" },
  "loading": { en: "Loading...", bn: "লোড হচ্ছে..." },
  "save": { en: "Save", bn: "সংরক্ষণ" },
  "cancel": { en: "Cancel", bn: "বাতিল" },
  "delete": { en: "Delete", bn: "মুছুন" },
  "edit": { en: "Edit", bn: "সম্পাদনা" },
  "add": { en: "Add", bn: "যোগ করুন" },
  "update": { en: "Update", bn: "আপডেট" },
  "submit": { en: "Submit", bn: "জমা দিন" },
  "confirm": { en: "Confirm", bn: "নিশ্চিত করুন" },
  "close": { en: "Close", bn: "বন্ধ করুন" },
  "view": { en: "View", bn: "দেখুন" },
  "view_all": { en: "View All", bn: "সব দেখুন" },
  "details": { en: "Details", bn: "বিস্তারিত" },
  "search_action": { en: "Search", bn: "অনুসন্ধান" },
  "filter": { en: "Filter", bn: "ফিল্টার" },
  "sort": { en: "Sort", bn: "সাজান" },
  "export": { en: "Export", bn: "এক্সপোর্ট" },
  "import": { en: "Import", bn: "ইম্পোর্ট" },
  "refresh": { en: "Refresh", bn: "রিফ্রেশ" },
  "back": { en: "Back", bn: "পিছনে" },
  "next": { en: "Next", bn: "পরবর্তী" },
  "previous": { en: "Previous", bn: "পূর্ববর্তী" },
  "yes": { en: "Yes", bn: "হ্যাঁ" },
  "no": { en: "No", bn: "না" },
  "none": { en: "None", bn: "কোনটি নয়" },
  "select": { en: "Select", bn: "নির্বাচন করুন" },
  "required": { en: "Required", bn: "প্রয়োজন" },
  "optional": { en: "Optional", bn: "ঐচ্ছিক" },
  "success": { en: "Success", bn: "সফল" },
  "error": { en: "Error", bn: "ত্রুটি" },
  "warning": { en: "Warning", bn: "সতর্কতা" },
  "info": { en: "Info", bn: "তথ্য" },
  "today": { en: "Today", bn: "আজ" },
  "yesterday": { en: "Yesterday", bn: "গতকাল" },
  "this_month": { en: "This Month", bn: "এই মাস" },
  "last_month": { en: "Last Month", bn: "গত মাস" },
  "just_now": { en: "Just now", bn: "এইমাত্র" },
  "min_ago": { en: "min ago", bn: "মিনিট আগে" },
  "hour_ago": { en: "hour ago", bn: "ঘণ্টা আগে" },
  "hours_ago": { en: "hours ago", bn: "ঘণ্টা আগে" },
  "day_ago": { en: "day ago", bn: "দিন আগে" },
  "days_ago": { en: "days ago", bn: "দিন আগে" },
  "active": { en: "Active", bn: "সক্রিয়" },
  "inactive": { en: "Inactive", bn: "নিষ্ক্রিয়" },
  "pending": { en: "Pending", bn: "অপেক্ষমাণ" },
  "completed": { en: "Completed", bn: "সম্পন্ন" },
  "failed": { en: "Failed", bn: "ব্যর্থ" },
  "taka": { en: "Taka", bn: "টাকা" },
  "kg": { en: "kg", bn: "কেজি" },
  "pcs": { en: "pcs", bn: "পিস" },
  "unit": { en: "unit", bn: "ইউনিট" },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("app-language", language);
  }, [language]);

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) return key;
    return translation[language] || translation.en || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
